import mongoose from 'mongoose';
import { CaptionPreset } from '../models/CaptionPreset';
import { logger } from '../utils/logger';
import { CaptionPresetController } from '../controllers/captionpreset.controller';

const CAPTION_PRESETS = [
  // ========== FEATURED STYLE ==========
  {
    id: "indigo-italic",
    name: "Indigo Italic",
    description: "Bold italic captions with indigo highlights",
    category: "featured",
    tags: ["bold", "italic", "featured"],
    usageCount: 0,
    isSystem: true,
    isPublic: true,
    styles: {
      fontFamily: "Passion One",
      fontWeight: 700,
      fillColor: "#FFFFFF",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 8,
      strokeOpacity: 1,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowOpacity: 0.8,
      shadowOffsetX: 5,
      shadowOffsetY: 5,
      shadowBlur: 0,
      highlightStyle: "color",
      highlightColor: "#6366F1",
      inactiveColor: "#FFFFFF",
      inactiveOpacity: 1,
      displayMode: "line",
      lineHeight: 1,
      wordsPerLine: 5,
      linesPerPage: 1,
      upcomingOpacity: 1,
    },
    previewStyles: {
      fontFamily: "'Passion One', cursive",
      textColor: "#FFFFFF",
      highlightColor: "#6366F1",
      strokeColor: "#000000",
      strokeWidth: 6,
      fontWeight: 700,
      italic: true,
      textShadow: "5px 5px 0px rgba(0,0,0,0.8)",
    },
  },

  // ========== BOLD IMPACT FONTS ==========
  {
    id: "impact-bold",
    name: "Impact Bold",
    description: "Bold impact font with yellow highlights",
    category: "bold-impact",
    tags: ["bold", "impact"],
    usageCount: 0,
    isSystem: true,
    isPublic: true,
    styles: {
      fontFamily: "Oswald",
      fontWeight: 700,
      fillColor: "#FFFFFF",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 4,
      strokeOpacity: 1,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowOpacity: 0.8,
      shadowOffsetX: 5,
      shadowOffsetY: 5,
      shadowBlur: 0,
      highlightStyle: "color",
      highlightColor: "#FFFF00",
      displayMode: "line",
      lineHeight: 1,
      wordsPerLine: 5,
      linesPerPage: 1,
      upcomingOpacity: 1,
      inactiveOpacity: 1,
      inactiveColor: "#FFFFFF",
    },
    previewStyles: {
      fontFamily: "'Oswald', sans-serif",
      textColor: "#FFFFFF",
      highlightColor: "#FFFF00",
      strokeColor: "#000000",
      strokeWidth: 3,
      fontWeight: 700,
      textShadow: "5px 5px 0px rgba(0,0,0,0.8)",
    },
  },
  {
    id: "bebas-fire",
    name: "Cookie",
    description: "Elegant script font with red highlights",
    category: "script",
    tags: ["script", "elegant"],
    usageCount: 0,
    isSystem: true,
    isPublic: true,
    styles: {
      fontFamily: "Cookie",
      fontWeight: 400,
      fillColor: "#FFFFFF",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 5,
      strokeOpacity: 1,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowOpacity: 0.8,
      shadowOffsetX: 5,
      shadowOffsetY: 5,
      shadowBlur: 0,
      backgroundXPadding: 27,
      backgroundYPadding: 11,
      highlightStyle: "color",
      highlightColor: "#ff0000",
      displayMode: "line",
      lineHeight: 1,
      wordsPerLine: 5,
      linesPerPage: 1,
      upcomingOpacity: 0.79,
      inactiveOpacity: 1,
      inactiveColor: "#FFFFFF",
    },
    previewStyles: {
      fontFamily: "'Cookie', cursive",
      textColor: "#FFFFFF",
      highlightColor: "#ff0000",
      strokeColor: "#000000",
      strokeWidth: 4,
      fontWeight: 400,
      textShadow: "5px 5px 0px rgba(0,0,0,0.8)",
    },
  },
  {
    id: "bangers-pop",
    name: "Comic Pop",
    description: "Fun comic style with orange highlights",
    category: "comic",
    tags: ["comic", "fun"],
    usageCount: 0,
     isSystem: true,
    isPublic: true, 
    styles: {
      fontFamily: "Bangers",
      fontWeight: 400,
      fillColor: "#FFFFFF",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 4,
      strokeOpacity: 1,
      highlightStyle: "color",
      highlightColor: "#F97316",
      displayMode: "line",
      lineHeight: 1,
    },
    previewStyles: {
      fontFamily: "'Bangers', cursive",
      textColor: "#FFFFFF",
      highlightColor: "#F97316",
      strokeColor: "#000000",
      strokeWidth: 3,
      fontWeight: 400,
    },
  },

  // ========== MODERN SANS ==========
  {
    id: "montserrat-bold",
    name: "Montserrat Bold",
    description: "Modern slab serif with blue highlights",
    category: "modern-sans",
    tags: ["modern", "bold"],
    usageCount: 0,
    isSystem: true,
    isPublic: true,
    styles: {
      fontFamily: "Alfa Slab One",
      fontWeight: 400,
      fillColor: "#FFFFFF",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 6,
      strokeOpacity: 1,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowOpacity: 0.8,
      shadowOffsetX: -5,
      shadowOffsetY: 5,
      shadowBlur: 0,
      highlightStyle: "color",
      highlightColor: "#3B82F6",
      displayMode: "line",
      lineHeight: 1,
      wordsPerLine: 5,
      linesPerPage: 1,
      upcomingOpacity: 0.71,
      inactiveOpacity: 1,
      inactiveColor: "#FFFFFF",
    },
    previewStyles: {
      fontFamily: "'Alfa Slab One', cursive",
      textColor: "#FFFFFF",
      highlightColor: "#3B82F6",
      strokeColor: "#000000",
      strokeWidth: 5,
      fontWeight: 400,
      textShadow: "-5px 5px 0px rgba(0,0,0,0.8)",
    },
  },
  {
    id: "poppins-clean",
    name: "Poppins Clean",
    description: "Clean modern font with white background",
    category: "modern-sans",
    tags: ["clean", "modern"],
    usageCount: 0,
    isSystem: true,
    isPublic: true,
    styles: {
      fontFamily: "Poppins",
      fontWeight: 700,
      fillColor: "#000000",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 2,
      strokeOpacity: 1,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowOpacity: 0.8,
      shadowOffsetX: 5,
      shadowOffsetY: 5,
      shadowBlur: 0,
      backgroundColor: "#FFFFFF",
      backgroundXPadding: 20,
      backgroundYPadding: 12,
      backgroundBorderRadius: 8,
      highlightStyle: "color",
      highlightColor: "#ffffff",
      displayMode: "line",
      lineHeight: 1,
      wordsPerLine: 5,
      linesPerPage: 1,
      upcomingOpacity: 1,
      inactiveOpacity: 1,
      inactiveColor: "#FFFFFF",
    },
    previewStyles: {
      fontFamily: "'Poppins', sans-serif",
      textColor: "#000000",
      highlightColor: "#ffffff",
      backgroundColor: "#FFFFFF",
      backgroundPadding: 14,
      backgroundRadius: 8,
      fontWeight: 700,
      textShadow: "5px 5px 0px rgba(0,0,0,0.8)",
    },
  },
  {
    id: "inter-minimal",
    name: "Inter Minimal",
    description: "Minimal design with cyan highlights",
    category: "minimal",
    tags: ["minimal", "clean"],
    usageCount: 0,
    isSystem: true,
    isPublic: true,
    styles: {
      fontFamily: "Inter",
      fontWeight: 600,
      fillColor: "#FFFFFF",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 4,
      strokeOpacity: 1,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowOpacity: 0.8,
      shadowOffsetX: 5,
      shadowOffsetY: 5,
      shadowBlur: 0,
      backgroundColor: "rgba(0,0,0,0.7)",
      backgroundXPadding: 16,
      backgroundYPadding: 10,
      backgroundBorderRadius: 6,
      highlightStyle: "color",
      highlightColor: "#00D4FF",
      displayMode: "line",
      lineHeight: 1,
      wordsPerLine: 5,
      linesPerPage: 1,
      upcomingOpacity: 1,
      inactiveOpacity: 1,
      inactiveColor: "#FFFFFF",
    },
    previewStyles: {
      fontFamily: "'Inter', sans-serif",
      textColor: "#FFFFFF",
      highlightColor: "#00D4FF",
      backgroundColor: "rgba(0,0,0,0.7)",
      backgroundPadding: 12,
      backgroundRadius: 6,
      fontWeight: 600,
      textShadow: "5px 5px 0px rgba(0,0,0,0.8)",
    },
  },

  // ========== DISPLAY & CREATIVE ==========
  {
    id: "righteous-glow",
    name: "Righteous Glow",
    isSystem: true,
    isPublic: true,
    styles: {
      fontFamily: "Righteous",
      fontWeight: 400,
      fillColor: "#FFFFFF",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 6,
      strokeOpacity: 1,
      shadowEnabled: true,
      shadowColor: "#00FFFF",
      shadowOpacity: 0.8,
      shadowOffsetX: 5,
      shadowOffsetY: 5,
      shadowBlur: 0,
      highlightStyle: "glow",
      highlightColor: "#00FFFF",
      displayMode: "line",
      lineHeight: 1,
      wordsPerLine: 5,
      linesPerPage: 1,
      upcomingOpacity: 1,
      inactiveOpacity: 1,
      inactiveColor: "#FFFFFF",
    },
    previewStyles: {
      fontFamily: "'Righteous', cursive",
      textColor: "#FFFFFF",
      highlightColor: "#00FFFF",
      strokeColor: "#000000",
      strokeWidth: 4,
      fontWeight: 400,
      textShadow: "5px 5px 0px rgba(0,0,0,0.8), 0 0 20px #00FFFF",
    },
  },
  {
    id: "passion-one",
    name: "Passion One",
    isSystem: true,
    isPublic: true,
    styles: {
      fontFamily: "Passion One",
      fontWeight: 700,
      fillColor: "#FFFFFF",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 8,
      strokeOpacity: 1,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowOpacity: 0.8,
      shadowOffsetX: 5,
      shadowOffsetY: 5,
      shadowBlur: 0,
      highlightStyle: "color",
      highlightColor: "#A855F7",
      displayMode: "line",
      lineHeight: 1,
      wordsPerLine: 5,
      linesPerPage: 1,
      upcomingOpacity: 1,
      inactiveOpacity: 1,
      inactiveColor: "#FFFFFF",
    },
    previewStyles: {
      fontFamily: "'Passion One', cursive",
      textColor: "#FFFFFF",
      highlightColor: "#A855F7",
      strokeColor: "#000000",
      strokeWidth: 6,
      fontWeight: 700,
      textShadow: "5px 5px 0px rgba(0,0,0,0.8)",
    },
  },
  {
    id: "rubik-mono",
    name: "Rubik Mono",
    isSystem: true,
    isPublic: true,
    styles: {
      fontFamily: "Rubik Mono One",
      fontWeight: 400,
      fillColor: "#00FF88",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 6,
      strokeOpacity: 1,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowOpacity: 0.8,
      shadowOffsetX: 5,
      shadowOffsetY: 5,
      shadowBlur: 0,
      highlightStyle: "glow",
      highlightColor: "#00FF88",
      displayMode: "line",
      lineHeight: 1,
      wordsPerLine: 5,
      linesPerPage: 1,
      upcomingOpacity: 1,
      inactiveOpacity: 1,
      inactiveColor: "#FFFFFF",
    },
    previewStyles: {
      fontFamily: "'Rubik Mono One', sans-serif",
      textColor: "#00FF88",
      highlightColor: "#00FF88",
      strokeColor: "#000000",
      strokeWidth: 4,
      fontWeight: 400,
      textShadow: "5px 5px 0px rgba(0,0,0,0.8), 0 0 15px #00FF88",
    },
  },

  // ========== SCRIPT & HANDWRITTEN ==========
  { 
    id: "permanent-marker",
    name: "Marker Style",
    isSystem: true,
    isPublic: true,
    styles: {
      fontFamily: "Permanent Marker",
      fontWeight: 400,
      fillColor: "#FFFFFF",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 6,
      strokeOpacity: 1,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowOpacity: 0.8,
      shadowOffsetX: 5,
      shadowOffsetY: 5,
      shadowBlur: 0,
      highlightStyle: "color",
      highlightColor: "#FACC15",
      displayMode: "line",
      lineHeight: 1,
      wordsPerLine: 5,
      linesPerPage: 1,
      upcomingOpacity: 1,
      inactiveOpacity: 1,
      inactiveColor: "#FFFFFF",
    },
    previewStyles: {
      fontFamily: "'Permanent Marker', cursive",
      textColor: "#FFFFFF",
      highlightColor: "#FACC15",
      strokeColor: "#000000",
      strokeWidth: 4,
      fontWeight: 400,
      textShadow: "5px 5px 0px rgba(0,0,0,0.8)",
    },
  },
  {
    id: "caveat-casual",
    name: "Caveat Casual",
    isSystem: true,
    isPublic: true,
    styles: {
      fontFamily: "Caveat",
      fontWeight: 700,
      fillColor: "#FFFFFF",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 6,
      strokeOpacity: 1,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowOpacity: 0.8,
      shadowOffsetX: 5,
      shadowOffsetY: 5,
      shadowBlur: 0,
      highlightStyle: "color",
      highlightColor: "#EC4899",
      displayMode: "line",
      lineHeight: 1,
      wordsPerLine: 5,
      linesPerPage: 1,
      upcomingOpacity: 1,
      inactiveOpacity: 1,
      inactiveColor: "#FFFFFF",
    },
    previewStyles: {
      fontFamily: "'Caveat', cursive",
      textColor: "#FFFFFF",
      highlightColor: "#EC4899",
      strokeColor: "#000000",
      strokeWidth: 4,
      fontWeight: 700,
      textShadow: "5px 5px 0px rgba(0,0,0,0.8)",
    },
  },

  // ========== BOLD BACKGROUNDS ==========
  {
    id: "archivo-black",
    name: "Archivo Black",
    isSystem: true,
    isPublic: true,
    styles: {
      fontFamily: "Archivo Black",
      fontWeight: 400,
      fillColor: "#000000",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 6,
      strokeOpacity: 1,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowOpacity: 0.8,
      shadowOffsetX: 5,
      shadowOffsetY: 5,
      shadowBlur: 0,
      backgroundColor: "#FACC15",
      backgroundXPadding: 18,
      backgroundYPadding: 10,
      backgroundBorderRadius: 4,
      highlightStyle: "background",
      highlightColor: "#000000",
      highlightBackgroundColor: "#EF4444",
      displayMode: "line",
      lineHeight: 1,
      wordsPerLine: 5,
      linesPerPage: 1,
      upcomingOpacity: 1,
      inactiveOpacity: 1,
      inactiveColor: "#FFFFFF",
    },
    previewStyles: {
      fontFamily: "'Archivo Black', sans-serif",
      textColor: "#000000",
      highlightColor: "#000000",
      backgroundColor: "#FACC15",
      backgroundPadding: 12,
      backgroundRadius: 4,
      fontWeight: 400,
      textShadow: "5px 5px 0px rgba(0,0,0,0.8)",
    },
  },
  {
    id: "russo-one",
    name: "Russo One",
    isSystem: true,
    isPublic: true,
    styles: {
      fontFamily: "Russo One",
      fontWeight: 400,
      fillColor: "#FFFFFF",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 6,
      strokeOpacity: 1,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowOpacity: 0.8,
      shadowOffsetX: 5,
      shadowOffsetY: 5,
      shadowBlur: 0,
      highlightStyle: "color",
      highlightColor: "#22C55E",
      displayMode: "line",
      lineHeight: 1,
      wordsPerLine: 5,
      linesPerPage: 1,
      upcomingOpacity: 1,
      inactiveOpacity: 1,
      inactiveColor: "#FFFFFF",
    },
    previewStyles: {
      fontFamily: "'Russo One', sans-serif",
      textColor: "#FFFFFF",
      highlightColor: "#22C55E",
      strokeColor: "#000000",
      strokeWidth: 4,
      fontWeight: 400,
      textShadow: "5px 5px 0px rgba(0,0,0,0.8)",
    },
  },

  // ========== GRADIENT & NEON STYLES ==========
  {
    id: "teko-gradient",
    name: "Teko Sunset",
    isSystem: true,
    isPublic: true,
    styles: {
      fontFamily: "Teko",
      fontWeight: 600,
      fillColor: "#FFFFFF",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 8,
      strokeOpacity: 1,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowOpacity: 0.8,
      shadowOffsetX: 5,
      shadowOffsetY: 5,
      shadowBlur: 0,
      highlightStyle: "color",
      highlightColor: "#F97316",
      displayMode: "line",
      lineHeight: 1,
      wordsPerLine: 5,
      linesPerPage: 1,
      upcomingOpacity: 1,
      inactiveOpacity: 1,
      inactiveColor: "#FFFFFF",
    },
    previewStyles: {
      fontFamily: "'Teko', sans-serif",
      textColor: "#FFFFFF",
      highlightColor: "#F97316",
      strokeColor: "#000000",
      strokeWidth: 6,
      fontWeight: 600,
      textShadow: "5px 5px 0px rgba(0,0,0,0.8)",
      gradient: "linear-gradient(90deg, #EF4444, #F97316, #FBBF24)",
    },
  },
  {
    id: "bungee-neon",
    name: "Bungee Neon",
    isSystem: true,
    isPublic: true,
    styles: {
      fontFamily: "Bungee",
      fontWeight: 400,
      fillColor: "#FFFFFF",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 6,
      strokeOpacity: 1,
      shadowEnabled: true,
      shadowColor: "#EC4899",
      shadowOpacity: 0.8,
      shadowOffsetX: 5,
      shadowOffsetY: 5,
      shadowBlur: 0,
      highlightStyle: "glow",
      highlightColor: "#EC4899",
      displayMode: "line",
      lineHeight: 1,
      wordsPerLine: 5,
      linesPerPage: 1,
      upcomingOpacity: 1,
      inactiveOpacity: 1,
      inactiveColor: "#FFFFFF",
    },
    previewStyles: {
      fontFamily: "'Bungee', cursive",
      textColor: "#FFFFFF",
      highlightColor: "#EC4899",
      strokeColor: "#000000",
      strokeWidth: 4,
      fontWeight: 400,
      textShadow: "5px 5px 0px rgba(0,0,0,0.8), 0 0 20px #EC4899",
    },
  },

  // ========== CLASSIC & ELEGANT ==========
  {
    id: "playfair-elegant",
    name: "Playfair Elegant",
    isSystem: true,
    isPublic: true,
    styles: {
      fontFamily: "Playfair Display",
      fontWeight: 700,
      fillColor: "#FFFFFF",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 2,
      strokeOpacity: 1,
      highlightStyle: "color",
      highlightColor: "#D4AF37",
      displayMode: "line",
      lineHeight: 1,
    },
    previewStyles: {
      fontFamily: "'Playfair Display', serif",
      textColor: "#FFFFFF",
      highlightColor: "#D4AF37",
      strokeColor: "#000000",
      strokeWidth: 1,
      fontWeight: 700,
    },
  },
  {
    id: "anton-classic",
    name: "Anton Classic",
    isSystem: true,
    isPublic: true,
    styles: {
      fontFamily: "Anton",
      fontWeight: 400,
      fillColor: "#FFFFFF",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 4,
      strokeOpacity: 1,
      highlightStyle: "color",
      highlightColor: "#FFFF00",
      displayMode: "line",
      lineHeight: 1,
    },
    previewStyles: {
      fontFamily: "'Anton', sans-serif",
      textColor: "#FFFFFF",
      highlightColor: "#FFFF00",
      strokeColor: "#000000",
      strokeWidth: 3,
      fontWeight: 400,
    },
  },

  // ========== KARAOKE & SPECIAL ==========
  {
    id: "luckiest-guy",
    name: "Luckiest Guy",
    isSystem: true,
    isPublic: true,
    styles: {
      fontFamily: "Luckiest Guy",
      fontWeight: 400,
      fillColor: "#FFFFFF",
      strokeEnabled: true,
      strokeColor: "#1a1a2e",
      strokeWidth: 3,
      strokeOpacity: 1,
      highlightStyle: "color",
      highlightColor: "#FFD700",
      displayMode: "line",
      lineHeight: 1,
    },
    previewStyles: {
      fontFamily: "'Luckiest Guy', cursive",
      textColor: "#FFFFFF",
      highlightColor: "#FFD700",
      strokeColor: "#1a1a2e",
      strokeWidth: 2,
      fontWeight: 400,
    },
  },
  {
    id: "fredoka-fun",
    name: "Fredoka Fun",
    isSystem: true,
    isPublic: true,
    styles: {
      fontFamily: "Fredoka One",
      fontWeight: 400,
      fillColor: "#FFFFFF",
      strokeEnabled: true,
      strokeColor: "#8B5CF6",
      strokeWidth: 3,
      strokeOpacity: 1,
      highlightStyle: "color",
      highlightColor: "#A855F7",
      displayMode: "line",
      lineHeight: 1,
    },
    previewStyles: {
      fontFamily: "'Fredoka One', cursive",
      textColor: "#FFFFFF",
      highlightColor: "#A855F7",
      strokeColor: "#7C3AED",
      strokeWidth: 2,
      fontWeight: 400,
    },
  },

  // ========== NO BACKGROUND STYLES ==========
  {
    id: "clean-white",
    name: "Clean White",
    isSystem: true,
    isPublic: true,
    styles: {
      fontFamily: "Inter",
      fontWeight: 700,
      fillColor: "#FFFFFF",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 3,
      strokeOpacity: 1,
      highlightStyle: "color",
      highlightColor: "#FFFF00",
      displayMode: "line",
      lineHeight: 1,
    },
    previewStyles: {
      fontFamily: "'Inter', sans-serif",
      textColor: "#FFFFFF",
      highlightColor: "#FFFF00",
      strokeColor: "#000000",
      strokeWidth: 2,
      fontWeight: 700,
    },
  },
  {
    id: "bold-red",
    name: "Bold Red",
    isSystem: true,
    isPublic: true,
    styles: {
      fontFamily: "Oswald",
      fontWeight: 700,
      fillColor: "#FFFFFF",
      strokeEnabled: true,
      strokeColor: "#EF4444",
      strokeWidth: 6,
      strokeOpacity: 1,
      highlightStyle: "color",
      highlightColor: "#EF4444",
      displayMode: "line",
      lineHeight: 1,
    },
    previewStyles: {
      fontFamily: "'Oswald', sans-serif",
      textColor: "#FFFFFF",
      highlightColor: "#EF4444",
      strokeColor: "#EF4444",
      strokeWidth: 3,
      fontWeight: 700,
    },
  },
  {
    id: "neon-blue",
    name: "Neon Blue",
    isSystem: true,
    isPublic: true,
    styles: {
      fontFamily: "Righteous",
      fontWeight: 400,
      fillColor: "#FFFFFF",
      strokeEnabled: true,
      strokeColor: "#3B82F6",
      strokeWidth: 6,
      strokeOpacity: 1,
      shadowEnabled: true,
      shadowColor: "#3B82F6",
      shadowOpacity: 0.8,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      shadowBlur: 15,
      highlightStyle: "glow",
      highlightColor: "#3B82F6",
      displayMode: "line",
      lineHeight: 1,
    },
    previewStyles: {
      fontFamily: "'Righteous', cursive",
      textColor: "#FFFFFF",
      highlightColor: "#3B82F6",
      strokeColor: "#3B82F6",
      strokeWidth: 2,
      fontWeight: 400,
      textShadow: "0 0 15px #3B82F6",
    },
  },
  {
    id: "golden-bold",
    name: "Golden Bold",
    isSystem: true,
    isPublic: true,
    styles: {
      fontFamily: "Anton",
      fontWeight: 400,
      fillColor: "#FBBF24",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 8,
      strokeOpacity: 1,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowOpacity: 0.8,
      shadowOffsetX: 5,
      shadowOffsetY: 5,
      shadowBlur: 0,
      highlightStyle: "color",
      highlightColor: "#F97316",
      displayMode: "line",
      lineHeight: 1,
    },
    previewStyles: {
      fontFamily: "'Anton', sans-serif",
      textColor: "#FBBF24",
      highlightColor: "#F97316",
      strokeColor: "#000000",
      strokeWidth: 3,
      fontWeight: 400,
    },
  },
  {
    id: "simple-black",
    name: "Simple Black",
    isSystem: true,
    isPublic: true,
    styles: {
      fontFamily: "Montserrat",
      fontWeight: 800,
      fillColor: "#000000",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 8,
      strokeOpacity: 1,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowOpacity: 0.8,
      shadowOffsetX: 5,
      shadowOffsetY: 5,
      shadowBlur: 0,
      highlightStyle: "color",
      highlightColor: "#EF4444",
      displayMode: "line",
      lineHeight: 1,
    },
    previewStyles: {
      fontFamily: "'Montserrat', sans-serif",
      textColor: "#000000",
      highlightColor: "#EF4444",
      strokeColor: "#FFFFFF",
      strokeWidth: 1,
      fontWeight: 800,
    },
  },
  {
    id: "purple-glow",
    name: "Purple Glow",
    isSystem: true,
    isPublic: true,
    styles: {
      fontFamily: "Poppins",
      fontWeight: 700,
      fillColor: "#FFFFFF",
      strokeEnabled: true,
      strokeColor: "#8B5CF6",
      strokeWidth: 8,
      strokeOpacity: 1,
      shadowEnabled: true,
      shadowColor: "#A855F7",
      shadowOpacity: 0.7,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      shadowBlur: 12,
      highlightStyle: "glow",
      highlightColor: "#A855F7",
      displayMode: "line",
      lineHeight: 1,
    },
    previewStyles: {
      fontFamily: "'Poppins', sans-serif",
      textColor: "#FFFFFF",
      highlightColor: "#A855F7",
      strokeColor: "#8B5CF6",
      strokeWidth: 2,
      fontWeight: 700,
      textShadow: "0 0 12px #A855F7",
    },
  },
  {
    id: "comic-orange",
    name: "Comic Orange",
    isSystem: true,
    isPublic: true,
    styles: {
      fontFamily: "Bangers",
      fontWeight: 400,
      fillColor: "#FFFFFF",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 8,
      strokeOpacity: 1,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowOpacity: 0.8,
      shadowOffsetX: 5,
      shadowOffsetY: 5,
      shadowBlur: 0,
      highlightStyle: "color",
      highlightColor: "#F97316",
      displayMode: "line",
      lineHeight: 1,
    },
    previewStyles: {
      fontFamily: "'Bangers', cursive",
      textColor: "#FFFFFF",
      highlightColor: "#F97316",
      strokeColor: "#F97316",
      strokeWidth: 3,
      fontWeight: 400,
    },
  },
  {
    id: "green-pop",
    name: "Green Pop",
    isSystem: true,
    isPublic: true,
    styles: {
      fontFamily: "Teko",
      fontWeight: 600,
      fillColor: "#FFFFFF",
      strokeColor: "#22C55E",
      strokeWidth: 3,
      highlightStyle: "color",
      highlightColor: "#22C55E",
      displayMode: "line",
      lineHeight: 1,
    },
    previewStyles: {
      fontFamily: "'Teko', sans-serif",
      textColor: "#FFFFFF",
      highlightColor: "#22C55E",
      strokeColor: "#22C55E",
      strokeWidth: 2,
      fontWeight: 600,
    },
  },
  {
    id: "bangers-shadow",
    name: "Bangers Shadow",
    isSystem: true,
    isPublic: true,
        styles: {
      fontFamily: "Bangers",
      fontWeight: 400,
      fillColor: "#FFFFFF",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 8,
      strokeOpacity: 1,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowOpacity: 0.8,
      shadowOffsetX: 5,
      shadowOffsetY: 5,
      shadowBlur: 0,
      backgroundBorderRadius: 7,
      backgroundXPadding: 39,
      backgroundYPadding: 11,
      highlightStyle: "color",
      highlightColor: "#F97316",
      displayMode: "line",
      lineHeight: 1,
      upcomingOpacity: 0.71,
      inactiveOpacity: 1,
    },
    previewStyles: {
      fontFamily: "'Bangers', cursive",
      textColor: "#FFFFFF",
      highlightColor: "#F97316",
      strokeColor: "#000000",
      strokeWidth: 6,
      fontWeight: 400,
      textShadow: "5px 5px 0px rgba(0,0,0,0.8)",
    },
  },
];

export async function seedCaptionPresets(): Promise<void> {
  try {
    logger.info('Starting caption presets seed...');


    // Insert new presets
    const insertedPresets = await CaptionPreset.insertMany(CAPTION_PRESETS);
    logger.info(`Inserted ${insertedPresets.length} caption presets`);

    // Log preset names
    const presetNames = insertedPresets.map(p => p.name);
    logger.info(`Seeded presets: ${presetNames.join(', ')}`);

  } catch (error) {
    logger.error('Error seeding caption presets:', error);
    throw error;
  }
}

